name: CI/CD for Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract short SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and Push Docker Image (with version)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            hoanghaaii/hari-news-fe:latest
            hoanghaaii/hari-news-fe:${{ env.SHORT_SHA }}

      - name: Deploy via SSH and Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/hari-news
            docker pull hoanghaaii/hari-news-fe:${{ env.SHORT_SHA }}
            docker tag hoanghaaii/hari-news-fe:${{ env.SHORT_SHA }} hoanghaaii/hari-news-fe:latest
            docker-compose up -d
